# Generated by Django 5.2.1 on 2025-05-24 16:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122, unique=True, verbose_name='Vendor Name')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
        ),
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122, unique=True, verbose_name='OS')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oses_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oses', to='commands.vendor', verbose_name='Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122, unique=True, verbose_name='Command Category')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='commands.category')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commands.vendor')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Commands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=255, unique=True, verbose_name='Command')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('example', models.TextField(blank=True, max_length=255, null=True, verbose_name='Example')),
                ('version', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid version number (e.g., 15.2.3, 15.2(3)T)', regex='^\\d+(\\.\\d+)+(\\([0-9]+\\))?([A-Za-z])?$')], verbose_name='Version')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='commands.category', verbose_name='Category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('os', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commands', to='commands.os', verbose_name='OS')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='commands.vendor', verbose_name='Vendor')),
            ],
            options={
                'ordering': ['-date_created'],
                'indexes': [models.Index(fields=['command'], name='commands_co_command_24c079_idx')],
            },
        ),
    ]
