# Generated by Django 5.2.1 on 2025-05-29 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0003_remove_commands_category_tag_commands_tag_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commands',
            name='os',
        ),
        migrations.AddField(
            model_name='commands',
            name='method',
            field=models.CharField(choices=[('BULK', 'Bulk'), ('SINGULAR', 'Singular')], default='SINGULAR', max_length=12, verbose_name='Creation Method'),
        ),
        migrations.AddField(
            model_name='commands',
            name='sub_command',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub Command'),
        ),
        migrations.CreateModel(
            name='CommandParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='commands.commands')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122, unique=True, verbose_name='Platform')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='commands.vendor', verbose_name='Vendor')),
            ],
        ),
        migrations.AddField(
            model_name='commands',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commands', to='commands.platform', verbose_name='Platform'),
        ),
        migrations.DeleteModel(
            name='OS',
        ),
    ]
