# Generated by Django 5.2.1 on 2025-05-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0004_remove_commands_os_commands_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=122, verbose_name='Command Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'vendor', 'parent')},
        ),
    ]
